repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: fmt-check
        name: rustfmt
        entry: cargo fmt -- --check
        language: system
        pass_filenames: false
        types: [rust]
      - id: clippy
        name: clippy
        entry: cargo clippy -- -D warnings
        language: system
        pass_filenames: false
        types: [rust]
