[package]
name = "ben-process"
version = "1.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/peterrrock2/ben-process"
keywords = ["redistricting", "gerrychain", "binary-ensemble"]
categories = ["command-line-utilities"]
description = "A command-line utility for processing redistricting ensembles compressed in the binary-ensemble format."

[lib]
crate-type = ["rlib", "cdylib"]

[features]
python = ["dep:pyo3"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow-array = "58.3.0"
ben = { package = "binary-ensemble", git = "https://github.com/peterrrock2/binary-ensemble", branch = "1.0.1" }
clap = "4.5.7"
env_logger = "0.11"
fastrand = "2.4.1"
geo = "0.33.1"
geo-traits = "0.3.0"
geo-types = "0.7.19"
geoparquet = "0.8.0"
indicatif = "0.18.4"
log = "0.4"
parquet = { version = "58.3.0", features = ["arrow"] }
polars = { version = "0.53.0", features = ["parquet"] }
proj = "0.31.0"
pyo3 = { version = "0.29.0", optional = true }
rand = "0.10.0"
rayon = "1.10.0"
serde = {version ="1.0.203", features = ["derive"]}
serde_json = "1.0.117"
thiserror = "2"
wkb = "0.9.2"
xxhash-rust = { version = "0.8", features = ["xxh3"] }

[[bin]]
name = "ben-process"
path = "src/main.rs"

[dev-dependencies]
tempfile = "3"
