[package]
name = "ben_process"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/peterrrock2/ben-process"
keywords = ["redistricting", "gerrychain", "binary-ensemble"]
categories = ["command-line-utilities"]
description = "A command-line utility for processing redistricting ensembles compressed in the binary-ensemble format."


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binary-ensemble = "0.3.0"
clap = "4.5.7"
env_logger = "0.11"
indicatif = "0.18.4"
log = "0.4"
polars = { version = "0.53.0", features = ["parquet"] }
rand = "0.10.0"
rayon = "1.10.0"
serde = {version ="1.0.203", features = ["derive"]}
serde_json = "1.0.117"
thiserror = "2"
xxhash-rust = { version = "0.8", features = ["xxh3"] }

[[bin]]
name = "ben-process"
path = "src/main.rs"

[dev-dependencies]
tempfile = "3"
